services:
  futu-opend:
    build:
      context: .
      args:
        FUTU_OPEND_VER: 9.4.5418
        BASE_IMG: ubuntu
    container_name: futu-opend
    stdin_open: true
    tty: true
    environment:
      - FUTU_OPEND_RSA_FILE_PATH=/.futu/futu.pem
    volumes:
      - $LOCAL_RSA_FILE_PATH:/.futu/futu.pem
    env_file:
      - .env
    ports:
      - 127.0.0.1:11111:11111
